version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - mynetwork

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:examplepassword@mongodb:27017
    networks:
      - mynetwork

  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
